name: Node.js CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - uses: actions/checkout@v3
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
          cache: npm
      - run: npm ci
      - run: 'npm run ci:test'
      - uses: romeovs/lcov-reporter-action@v0.2.19
        with:
          lcov-file: ./coverage/lcov.info
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
